version: "3.8"

volumes:
  certs:
    driver: local
  esData01:
    driver: local
  kibanaData:
    driver: local

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    labels:
      co.elastic.logs/module: elasticsearch
    volumes:
      - /elk/esData01:/usr/share/elasticsearch/data
    ports:
      - ${ES01_PORT}:9200
    environment:
      - node.name=es01
      - cluster.name=${CLUSTER_NAME}
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      #- bootstrap.memory_lock=true
    networks:
      - elastictest

  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    volumes:
      - /elk/kibanaData:/usr/share/kibana/data
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://es01:9200
    networks:
      - elastictest

networks:
  elastictest:
    driver: bridge
